server:
  port: 8080

logging:
  level:
    root: info
    com.aisino.social.mqtt.service.controller: DEBUG

##################
#  MQTT 配置
##################
# 用户名
mqtt:
  username: admin
# 密码
  password: public
# 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:61613
  url: tcp://172.16.1.204:31883
##################
#  MQTT 生产者
##################
# 连接服务器默认客户端ID
  producer:
    clientId: serverMqttProducer
# 默认的推送主题，实际可在调用接口时指定
    defaultTopic: producerDefaultTopic
##################
#  MQTT 消费者
##################
# 连接服务器默认客户端ID
  consumer:
    clientId: serverMqttConsumer
# 默认的接收主题，可以订阅多个Topic，逗号分隔
    defaultTopic: consumerDefaultTopic
    